//regenerates vendored pdf.js bundles
//run via node scripts/vendor-pdfjs.mjs

import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

//umd legacy build for old webviews
const VERSION = '3.11.174';

const outDir = join(fileURLToPath(new URL('.', import.meta.url)), '..', 'src', 'services', 'documents', 'vendor');
const work = mkdtempSync(join(tmpdir(), 'pdfjs-'));

execFileSync('npm', ['pack', `pdfjs-dist@${VERSION}`, '--silent'], { cwd: work, shell: true });
execFileSync('tar', ['-xzf', `pdfjs-dist-${VERSION}.tgz`], { cwd: work });

for (const [file, name] of [['pdf.min.js', 'pdfjsCore'], ['pdf.worker.min.js', 'pdfjsWorker']]) {
  const source = readFileSync(join(work, 'package', 'legacy', 'build', file), 'utf8');
  const banner = `//generated by scripts/vendor-pdfjs.mjs from pdfjs-dist@${VERSION} (${file})\n//do not edit\n`;
  writeFileSync(
    join(outDir, `${name}.ts`),
    `${banner}export const ${name.toUpperCase()}_SOURCE = ${JSON.stringify(source)};\n`
  );
}

console.log(`vendored pdfjs-dist@${VERSION} into ${outDir}`);
